[package]
name = "h264-reader"
version = "0.1.0"
authors = ["David Holroyd <dave@badgers-in-foil.co.uk>"]
description = "Reader for H264 bitsream syntax"
categories = [ "multimedia::video" ]
keywords = [ "H-264" ]
readme = "README.md"

[dependencies]
bitreader = "0.3.1"

[dev-dependencies]
hex-literal = "0.1.0"
hex-slice = "0.1.4"
